// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"fmt"
	"slash-admin/app/admin/ent/sysapi"
	"slash-admin/app/admin/ent/sysdictionary"
	"slash-admin/app/admin/ent/sysdictionarydetail"
	"slash-admin/app/admin/ent/sysmenu"
	"slash-admin/app/admin/ent/sysmenuparam"
	"slash-admin/app/admin/ent/sysoauthprovider"
	"slash-admin/app/admin/ent/sysrole"
	"slash-admin/app/admin/ent/systoken"
	"slash-admin/app/admin/ent/sysuser"
	"sync"
	"sync/atomic"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/schema"
	"github.com/99designs/gqlgen/graphql"
	"github.com/hashicorp/go-multierror"
	"golang.org/x/sync/semaphore"
)

// Noder wraps the basic Node method.
type Noder interface {
	Node(context.Context) (*Node, error)
}

// Node in the graph.
type Node struct {
	ID     uint64   `json:"id,omitempty"`     // node id.
	Type   string   `json:"type,omitempty"`   // node type.
	Fields []*Field `json:"fields,omitempty"` // node fields.
	Edges  []*Edge  `json:"edges,omitempty"`  // node edges.
}

// Field of a node.
type Field struct {
	Type  string `json:"type,omitempty"`  // field type.
	Name  string `json:"name,omitempty"`  // field name (as in struct).
	Value string `json:"value,omitempty"` // stringified value.
}

// Edges between two nodes.
type Edge struct {
	Type string   `json:"type,omitempty"` // edge type.
	Name string   `json:"name,omitempty"` // edge name.
	IDs  []uint64 `json:"ids,omitempty"`  // node ids (where this edge point to).
}

func (sa *SysApi) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     sa.ID,
		Type:   "SysApi",
		Fields: make([]*Field, 7),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(sa.Path); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "path",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sa.Description); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "description",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sa.APIGroup); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "api_group",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sa.Method); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "method",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sa.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sa.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sa.DeletedAt); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "time.Time",
		Name:  "deleted_at",
		Value: string(buf),
	}
	return node, nil
}

func (sd *SysDictionary) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     sd.ID,
		Type:   "SysDictionary",
		Fields: make([]*Field, 7),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(sd.Title); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "title",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sd.Name); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sd.Status); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "types.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sd.Desc); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "desc",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sd.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sd.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sd.DeletedAt); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "time.Time",
		Name:  "deleted_at",
		Value: string(buf),
	}
	return node, nil
}

func (sdd *SysDictionaryDetail) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     sdd.ID,
		Type:   "SysDictionaryDetail",
		Fields: make([]*Field, 9),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(sdd.Title); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "title",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sdd.Key); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "key",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sdd.Value); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "value",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sdd.Status); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "types.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sdd.Remark); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "remark",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sdd.OrderNo); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "uint32",
		Name:  "order_no",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sdd.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sdd.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sdd.DeletedAt); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "time.Time",
		Name:  "deleted_at",
		Value: string(buf),
	}
	return node, nil
}

func (sm *SysMenu) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     sm.ID,
		Type:   "SysMenu",
		Fields: make([]*Field, 13),
		Edges:  make([]*Edge, 3),
	}
	var buf []byte
	if buf, err = json.Marshal(sm.MenuLevel); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "uint32",
		Name:  "menu_level",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.MenuType); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "uint32",
		Name:  "menu_type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.ParentID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "uint64",
		Name:  "parent_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.Path); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "path",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.Name); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.Redirect); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "redirect",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.Component); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "component",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.OrderNo); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "uint32",
		Name:  "order_no",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.Disabled); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "bool",
		Name:  "disabled",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.Meta); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "types.MenuMeta",
		Name:  "meta",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sm.DeletedAt); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "time.Time",
		Name:  "deleted_at",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "SysRole",
		Name: "roles",
	}
	err = sm.QueryRoles().
		Select(sysrole.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "SysMenu",
		Name: "parent",
	}
	err = sm.QueryParent().
		Select(sysmenu.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "SysMenu",
		Name: "children",
	}
	err = sm.QueryChildren().
		Select(sysmenu.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (smp *SysMenuParam) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     smp.ID,
		Type:   "SysMenuParam",
		Fields: make([]*Field, 7),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(smp.MenuID); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "uint64",
		Name:  "menu_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(smp.Type); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(smp.Key); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "key",
		Value: string(buf),
	}
	if buf, err = json.Marshal(smp.Value); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "value",
		Value: string(buf),
	}
	if buf, err = json.Marshal(smp.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(smp.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(smp.DeletedAt); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "time.Time",
		Name:  "deleted_at",
		Value: string(buf),
	}
	return node, nil
}

func (sop *SysOauthProvider) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     sop.ID,
		Type:   "SysOauthProvider",
		Fields: make([]*Field, 12),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(sop.Name); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.ClientID); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "client_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.ClientSecret); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "client_secret",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.RedirectURL); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "redirect_url",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.Scopes); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "scopes",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.AuthURL); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "auth_url",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.TokenURL); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "token_url",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.AuthStyle); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "uint8",
		Name:  "auth_style",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.InfoURL); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "string",
		Name:  "info_url",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sop.DeletedAt); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "time.Time",
		Name:  "deleted_at",
		Value: string(buf),
	}
	return node, nil
}

func (sr *SysRole) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     sr.ID,
		Type:   "SysRole",
		Fields: make([]*Field, 9),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(sr.Name); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sr.Value); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "value",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sr.DefaultRouter); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "default_router",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sr.Status); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "types.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sr.Remark); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "remark",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sr.OrderNo); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "uint32",
		Name:  "order_no",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sr.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sr.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(sr.DeletedAt); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "time.Time",
		Name:  "deleted_at",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "SysMenu",
		Name: "menus",
	}
	err = sr.QueryMenus().
		Select(sysmenu.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (st *SysToken) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     st.ID,
		Type:   "SysToken",
		Fields: make([]*Field, 8),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(st.UUID); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "uuid",
		Value: string(buf),
	}
	if buf, err = json.Marshal(st.Token); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "token",
		Value: string(buf),
	}
	if buf, err = json.Marshal(st.Source); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "source",
		Value: string(buf),
	}
	if buf, err = json.Marshal(st.Status); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "types.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(st.ExpiredAt); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "time.Time",
		Name:  "expired_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(st.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(st.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(st.DeletedAt); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "time.Time",
		Name:  "deleted_at",
		Value: string(buf),
	}
	return node, nil
}

func (su *SysUser) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     su.ID,
		Type:   "SysUser",
		Fields: make([]*Field, 15),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(su.UUID); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "uuid",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.Username); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "username",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.Password); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "password",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.Nickname); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "nickname",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.SideMode); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "side_mode",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.Avatar); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "avatar",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.BaseColor); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "base_color",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.ActiveColor); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "active_color",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.RoleID); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "uint32",
		Name:  "role_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.Mobile); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "string",
		Name:  "mobile",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.Email); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "string",
		Name:  "email",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.Status); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "types.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(su.DeletedAt); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "time.Time",
		Name:  "deleted_at",
		Value: string(buf),
	}
	return node, nil
}

func (c *Client) Node(ctx context.Context, id uint64) (*Node, error) {
	n, err := c.Noder(ctx, id)
	if err != nil {
		return nil, err
	}
	return n.Node(ctx)
}

var errNodeInvalidID = &NotFoundError{"node"}

// NodeOption allows configuring the Noder execution using functional options.
type NodeOption func(*nodeOptions)

// WithNodeType sets the node Type resolver function (i.e. the table to query).
// If was not provided, the table will be derived from the universal-id
// configuration as described in: https://entgo.io/docs/migrate/#universal-ids.
func WithNodeType(f func(context.Context, uint64) (string, error)) NodeOption {
	return func(o *nodeOptions) {
		o.nodeType = f
	}
}

// WithFixedNodeType sets the Type of the node to a fixed value.
func WithFixedNodeType(t string) NodeOption {
	return WithNodeType(func(context.Context, uint64) (string, error) {
		return t, nil
	})
}

type nodeOptions struct {
	nodeType func(context.Context, uint64) (string, error)
}

func (c *Client) newNodeOpts(opts []NodeOption) *nodeOptions {
	nopts := &nodeOptions{}
	for _, opt := range opts {
		opt(nopts)
	}
	if nopts.nodeType == nil {
		nopts.nodeType = func(ctx context.Context, id uint64) (string, error) {
			return c.tables.nodeType(ctx, c.driver, id)
		}
	}
	return nopts
}

// Noder returns a Node by its id. If the NodeType was not provided, it will
// be derived from the id value according to the universal-id configuration.
//
//	c.Noder(ctx, id)
//	c.Noder(ctx, id, ent.WithNodeType(typeResolver))
func (c *Client) Noder(ctx context.Context, id uint64, opts ...NodeOption) (_ Noder, err error) {
	defer func() {
		if IsNotFound(err) {
			err = multierror.Append(err, entgql.ErrNodeNotFound(id))
		}
	}()
	table, err := c.newNodeOpts(opts).nodeType(ctx, id)
	if err != nil {
		return nil, err
	}
	return c.noder(ctx, table, id)
}

func (c *Client) noder(ctx context.Context, table string, id uint64) (Noder, error) {
	switch table {
	case sysapi.Table:
		query := c.SysApi.Query().
			Where(sysapi.ID(id))
		query, err := query.CollectFields(ctx, "SysApi")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case sysdictionary.Table:
		query := c.SysDictionary.Query().
			Where(sysdictionary.ID(id))
		query, err := query.CollectFields(ctx, "SysDictionary")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case sysdictionarydetail.Table:
		query := c.SysDictionaryDetail.Query().
			Where(sysdictionarydetail.ID(id))
		query, err := query.CollectFields(ctx, "SysDictionaryDetail")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case sysmenu.Table:
		query := c.SysMenu.Query().
			Where(sysmenu.ID(id))
		query, err := query.CollectFields(ctx, "SysMenu")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case sysmenuparam.Table:
		query := c.SysMenuParam.Query().
			Where(sysmenuparam.ID(id))
		query, err := query.CollectFields(ctx, "SysMenuParam")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case sysoauthprovider.Table:
		query := c.SysOauthProvider.Query().
			Where(sysoauthprovider.ID(id))
		query, err := query.CollectFields(ctx, "SysOauthProvider")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case sysrole.Table:
		query := c.SysRole.Query().
			Where(sysrole.ID(id))
		query, err := query.CollectFields(ctx, "SysRole")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case systoken.Table:
		query := c.SysToken.Query().
			Where(systoken.ID(id))
		query, err := query.CollectFields(ctx, "SysToken")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case sysuser.Table:
		query := c.SysUser.Query().
			Where(sysuser.ID(id))
		query, err := query.CollectFields(ctx, "SysUser")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	default:
		return nil, fmt.Errorf("cannot resolve noder from table %q: %w", table, errNodeInvalidID)
	}
}

func (c *Client) Noders(ctx context.Context, ids []uint64, opts ...NodeOption) ([]Noder, error) {
	switch len(ids) {
	case 1:
		noder, err := c.Noder(ctx, ids[0], opts...)
		if err != nil {
			return nil, err
		}
		return []Noder{noder}, nil
	case 0:
		return []Noder{}, nil
	}

	noders := make([]Noder, len(ids))
	errors := make([]error, len(ids))
	tables := make(map[string][]uint64)
	id2idx := make(map[uint64][]int, len(ids))
	nopts := c.newNodeOpts(opts)
	for i, id := range ids {
		table, err := nopts.nodeType(ctx, id)
		if err != nil {
			errors[i] = err
			continue
		}
		tables[table] = append(tables[table], id)
		id2idx[id] = append(id2idx[id], i)
	}

	for table, ids := range tables {
		nodes, err := c.noders(ctx, table, ids)
		if err != nil {
			for _, id := range ids {
				for _, idx := range id2idx[id] {
					errors[idx] = err
				}
			}
		} else {
			for i, id := range ids {
				for _, idx := range id2idx[id] {
					noders[idx] = nodes[i]
				}
			}
		}
	}

	for i, id := range ids {
		if errors[i] == nil {
			if noders[i] != nil {
				continue
			}
			errors[i] = entgql.ErrNodeNotFound(id)
		} else if IsNotFound(errors[i]) {
			errors[i] = multierror.Append(errors[i], entgql.ErrNodeNotFound(id))
		}
		ctx := graphql.WithPathContext(ctx,
			graphql.NewPathWithIndex(i),
		)
		graphql.AddError(ctx, errors[i])
	}
	return noders, nil
}

func (c *Client) noders(ctx context.Context, table string, ids []uint64) ([]Noder, error) {
	noders := make([]Noder, len(ids))
	idmap := make(map[uint64][]*Noder, len(ids))
	for i, id := range ids {
		idmap[id] = append(idmap[id], &noders[i])
	}
	switch table {
	case sysapi.Table:
		query := c.SysApi.Query().
			Where(sysapi.IDIn(ids...))
		query, err := query.CollectFields(ctx, "SysApi")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case sysdictionary.Table:
		query := c.SysDictionary.Query().
			Where(sysdictionary.IDIn(ids...))
		query, err := query.CollectFields(ctx, "SysDictionary")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case sysdictionarydetail.Table:
		query := c.SysDictionaryDetail.Query().
			Where(sysdictionarydetail.IDIn(ids...))
		query, err := query.CollectFields(ctx, "SysDictionaryDetail")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case sysmenu.Table:
		query := c.SysMenu.Query().
			Where(sysmenu.IDIn(ids...))
		query, err := query.CollectFields(ctx, "SysMenu")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case sysmenuparam.Table:
		query := c.SysMenuParam.Query().
			Where(sysmenuparam.IDIn(ids...))
		query, err := query.CollectFields(ctx, "SysMenuParam")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case sysoauthprovider.Table:
		query := c.SysOauthProvider.Query().
			Where(sysoauthprovider.IDIn(ids...))
		query, err := query.CollectFields(ctx, "SysOauthProvider")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case sysrole.Table:
		query := c.SysRole.Query().
			Where(sysrole.IDIn(ids...))
		query, err := query.CollectFields(ctx, "SysRole")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case systoken.Table:
		query := c.SysToken.Query().
			Where(systoken.IDIn(ids...))
		query, err := query.CollectFields(ctx, "SysToken")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case sysuser.Table:
		query := c.SysUser.Query().
			Where(sysuser.IDIn(ids...))
		query, err := query.CollectFields(ctx, "SysUser")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	default:
		return nil, fmt.Errorf("cannot resolve noders from table %q: %w", table, errNodeInvalidID)
	}
	return noders, nil
}

type tables struct {
	once  sync.Once
	sem   *semaphore.Weighted
	value atomic.Value
}

func (t *tables) nodeType(ctx context.Context, drv dialect.Driver, id uint64) (string, error) {
	tables, err := t.Load(ctx, drv)
	if err != nil {
		return "", err
	}
	idx := int(id / (1<<32 - 1))
	if idx < 0 || idx >= len(tables) {
		return "", fmt.Errorf("cannot resolve table from id %v: %w", id, errNodeInvalidID)
	}
	return tables[idx], nil
}

func (t *tables) Load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	t.once.Do(func() { t.sem = semaphore.NewWeighted(1) })
	if err := t.sem.Acquire(ctx, 1); err != nil {
		return nil, err
	}
	defer t.sem.Release(1)
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	tables, err := t.load(ctx, drv)
	if err == nil {
		t.value.Store(tables)
	}
	return tables, err
}

func (*tables) load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	rows := &sql.Rows{}
	query, args := sql.Dialect(drv.Dialect()).
		Select("type").
		From(sql.Table(schema.TypeTable)).
		OrderBy(sql.Asc("id")).
		Query()
	if err := drv.Query(ctx, query, args, rows); err != nil {
		return nil, err
	}
	defer rows.Close()
	var tables []string
	return tables, sql.ScanSlice(rows, &tables)
}
