// Code generated by ent, DO NOT EDIT.

package ent

import (
	"slash-admin/app/admin/ent/schema"
	"slash-admin/app/admin/ent/sysapi"
	"slash-admin/app/admin/ent/sysdictionary"
	"slash-admin/app/admin/ent/sysdictionarydetail"
	"slash-admin/app/admin/ent/sysoauthprovider"
	"slash-admin/app/admin/ent/sysrole"
	"slash-admin/app/admin/ent/systoken"
	"slash-admin/app/admin/ent/sysuser"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sysapiFields := schema.SysApi{}.Fields()
	_ = sysapiFields
	// sysapiDescMethod is the schema descriptor for method field.
	sysapiDescMethod := sysapiFields[4].Descriptor()
	// sysapi.DefaultMethod holds the default value on creation for the method field.
	sysapi.DefaultMethod = sysapiDescMethod.Default.(string)
	// sysapiDescCreatedAt is the schema descriptor for created_at field.
	sysapiDescCreatedAt := sysapiFields[5].Descriptor()
	// sysapi.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysapi.DefaultCreatedAt = sysapiDescCreatedAt.Default.(func() time.Time)
	// sysapiDescUpdatedAt is the schema descriptor for updated_at field.
	sysapiDescUpdatedAt := sysapiFields[6].Descriptor()
	// sysapi.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysapi.DefaultUpdatedAt = sysapiDescUpdatedAt.Default.(func() time.Time)
	// sysapi.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysapi.UpdateDefaultUpdatedAt = sysapiDescUpdatedAt.UpdateDefault.(func() time.Time)
	sysdictionaryFields := schema.SysDictionary{}.Fields()
	_ = sysdictionaryFields
	// sysdictionaryDescCreatedAt is the schema descriptor for created_at field.
	sysdictionaryDescCreatedAt := sysdictionaryFields[5].Descriptor()
	// sysdictionary.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysdictionary.DefaultCreatedAt = sysdictionaryDescCreatedAt.Default.(func() time.Time)
	// sysdictionaryDescUpdatedAt is the schema descriptor for updated_at field.
	sysdictionaryDescUpdatedAt := sysdictionaryFields[6].Descriptor()
	// sysdictionary.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysdictionary.DefaultUpdatedAt = sysdictionaryDescUpdatedAt.Default.(func() time.Time)
	// sysdictionary.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysdictionary.UpdateDefaultUpdatedAt = sysdictionaryDescUpdatedAt.UpdateDefault.(func() time.Time)
	sysdictionarydetailFields := schema.SysDictionaryDetail{}.Fields()
	_ = sysdictionarydetailFields
	// sysdictionarydetailDescOrderNo is the schema descriptor for order_no field.
	sysdictionarydetailDescOrderNo := sysdictionarydetailFields[6].Descriptor()
	// sysdictionarydetail.DefaultOrderNo holds the default value on creation for the order_no field.
	sysdictionarydetail.DefaultOrderNo = sysdictionarydetailDescOrderNo.Default.(uint32)
	// sysdictionarydetailDescCreatedAt is the schema descriptor for created_at field.
	sysdictionarydetailDescCreatedAt := sysdictionarydetailFields[7].Descriptor()
	// sysdictionarydetail.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysdictionarydetail.DefaultCreatedAt = sysdictionarydetailDescCreatedAt.Default.(func() time.Time)
	// sysdictionarydetailDescUpdatedAt is the schema descriptor for updated_at field.
	sysdictionarydetailDescUpdatedAt := sysdictionarydetailFields[8].Descriptor()
	// sysdictionarydetail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysdictionarydetail.DefaultUpdatedAt = sysdictionarydetailDescUpdatedAt.Default.(func() time.Time)
	// sysdictionarydetail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysdictionarydetail.UpdateDefaultUpdatedAt = sysdictionarydetailDescUpdatedAt.UpdateDefault.(func() time.Time)
	sysoauthproviderFields := schema.SysOauthProvider{}.Fields()
	_ = sysoauthproviderFields
	// sysoauthproviderDescCreatedAt is the schema descriptor for created_at field.
	sysoauthproviderDescCreatedAt := sysoauthproviderFields[10].Descriptor()
	// sysoauthprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysoauthprovider.DefaultCreatedAt = sysoauthproviderDescCreatedAt.Default.(func() time.Time)
	// sysoauthproviderDescUpdatedAt is the schema descriptor for updated_at field.
	sysoauthproviderDescUpdatedAt := sysoauthproviderFields[11].Descriptor()
	// sysoauthprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysoauthprovider.DefaultUpdatedAt = sysoauthproviderDescUpdatedAt.Default.(func() time.Time)
	// sysoauthprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysoauthprovider.UpdateDefaultUpdatedAt = sysoauthproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	sysroleFields := schema.SysRole{}.Fields()
	_ = sysroleFields
	// sysroleDescDefaultRouter is the schema descriptor for default_router field.
	sysroleDescDefaultRouter := sysroleFields[3].Descriptor()
	// sysrole.DefaultDefaultRouter holds the default value on creation for the default_router field.
	sysrole.DefaultDefaultRouter = sysroleDescDefaultRouter.Default.(string)
	// sysroleDescOrderNo is the schema descriptor for order_no field.
	sysroleDescOrderNo := sysroleFields[6].Descriptor()
	// sysrole.DefaultOrderNo holds the default value on creation for the order_no field.
	sysrole.DefaultOrderNo = sysroleDescOrderNo.Default.(uint32)
	// sysroleDescCreatedAt is the schema descriptor for created_at field.
	sysroleDescCreatedAt := sysroleFields[7].Descriptor()
	// sysrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysrole.DefaultCreatedAt = sysroleDescCreatedAt.Default.(func() time.Time)
	// sysroleDescUpdatedAt is the schema descriptor for updated_at field.
	sysroleDescUpdatedAt := sysroleFields[8].Descriptor()
	// sysrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysrole.DefaultUpdatedAt = sysroleDescUpdatedAt.Default.(func() time.Time)
	// sysrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysrole.UpdateDefaultUpdatedAt = sysroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	systokenFields := schema.SysToken{}.Fields()
	_ = systokenFields
	// systokenDescCreatedAt is the schema descriptor for created_at field.
	systokenDescCreatedAt := systokenFields[6].Descriptor()
	// systoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	systoken.DefaultCreatedAt = systokenDescCreatedAt.Default.(func() time.Time)
	// systokenDescUpdatedAt is the schema descriptor for updated_at field.
	systokenDescUpdatedAt := systokenFields[7].Descriptor()
	// systoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systoken.DefaultUpdatedAt = systokenDescUpdatedAt.Default.(func() time.Time)
	// systoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systoken.UpdateDefaultUpdatedAt = systokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	sysuserFields := schema.SysUser{}.Fields()
	_ = sysuserFields
	// sysuserDescSideMode is the schema descriptor for side_mode field.
	sysuserDescSideMode := sysuserFields[5].Descriptor()
	// sysuser.DefaultSideMode holds the default value on creation for the side_mode field.
	sysuser.DefaultSideMode = sysuserDescSideMode.Default.(string)
	// sysuserDescBaseColor is the schema descriptor for base_color field.
	sysuserDescBaseColor := sysuserFields[7].Descriptor()
	// sysuser.DefaultBaseColor holds the default value on creation for the base_color field.
	sysuser.DefaultBaseColor = sysuserDescBaseColor.Default.(string)
	// sysuserDescActiveColor is the schema descriptor for active_color field.
	sysuserDescActiveColor := sysuserFields[8].Descriptor()
	// sysuser.DefaultActiveColor holds the default value on creation for the active_color field.
	sysuser.DefaultActiveColor = sysuserDescActiveColor.Default.(string)
	// sysuserDescRoleID is the schema descriptor for role_id field.
	sysuserDescRoleID := sysuserFields[9].Descriptor()
	// sysuser.DefaultRoleID holds the default value on creation for the role_id field.
	sysuser.DefaultRoleID = sysuserDescRoleID.Default.(uint32)
	// sysuserDescCreatedAt is the schema descriptor for created_at field.
	sysuserDescCreatedAt := sysuserFields[13].Descriptor()
	// sysuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysuser.DefaultCreatedAt = sysuserDescCreatedAt.Default.(func() time.Time)
	// sysuserDescUpdatedAt is the schema descriptor for updated_at field.
	sysuserDescUpdatedAt := sysuserFields[14].Descriptor()
	// sysuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysuser.DefaultUpdatedAt = sysuserDescUpdatedAt.Default.(func() time.Time)
	// sysuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysuser.UpdateDefaultUpdatedAt = sysuserDescUpdatedAt.UpdateDefault.(func() time.Time)
}
