// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"slash-admin/app/admin/ent/predicate"
	"slash-admin/app/admin/ent/sysmenuparam"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysMenuParamQuery is the builder for querying SysMenuParam entities.
type SysMenuParamQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.SysMenuParam
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SysMenuParamQuery builder.
func (smpq *SysMenuParamQuery) Where(ps ...predicate.SysMenuParam) *SysMenuParamQuery {
	smpq.predicates = append(smpq.predicates, ps...)
	return smpq
}

// Limit adds a limit step to the query.
func (smpq *SysMenuParamQuery) Limit(limit int) *SysMenuParamQuery {
	smpq.limit = &limit
	return smpq
}

// Offset adds an offset step to the query.
func (smpq *SysMenuParamQuery) Offset(offset int) *SysMenuParamQuery {
	smpq.offset = &offset
	return smpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (smpq *SysMenuParamQuery) Unique(unique bool) *SysMenuParamQuery {
	smpq.unique = &unique
	return smpq
}

// Order adds an order step to the query.
func (smpq *SysMenuParamQuery) Order(o ...OrderFunc) *SysMenuParamQuery {
	smpq.order = append(smpq.order, o...)
	return smpq
}

// First returns the first SysMenuParam entity from the query.
// Returns a *NotFoundError when no SysMenuParam was found.
func (smpq *SysMenuParamQuery) First(ctx context.Context) (*SysMenuParam, error) {
	nodes, err := smpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sysmenuparam.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (smpq *SysMenuParamQuery) FirstX(ctx context.Context) *SysMenuParam {
	node, err := smpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SysMenuParam ID from the query.
// Returns a *NotFoundError when no SysMenuParam ID was found.
func (smpq *SysMenuParamQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = smpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sysmenuparam.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (smpq *SysMenuParamQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := smpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SysMenuParam entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SysMenuParam entity is found.
// Returns a *NotFoundError when no SysMenuParam entities are found.
func (smpq *SysMenuParamQuery) Only(ctx context.Context) (*SysMenuParam, error) {
	nodes, err := smpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sysmenuparam.Label}
	default:
		return nil, &NotSingularError{sysmenuparam.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (smpq *SysMenuParamQuery) OnlyX(ctx context.Context) *SysMenuParam {
	node, err := smpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SysMenuParam ID in the query.
// Returns a *NotSingularError when more than one SysMenuParam ID is found.
// Returns a *NotFoundError when no entities are found.
func (smpq *SysMenuParamQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = smpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sysmenuparam.Label}
	default:
		err = &NotSingularError{sysmenuparam.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (smpq *SysMenuParamQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := smpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SysMenuParams.
func (smpq *SysMenuParamQuery) All(ctx context.Context) ([]*SysMenuParam, error) {
	if err := smpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return smpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (smpq *SysMenuParamQuery) AllX(ctx context.Context) []*SysMenuParam {
	nodes, err := smpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SysMenuParam IDs.
func (smpq *SysMenuParamQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := smpq.Select(sysmenuparam.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (smpq *SysMenuParamQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := smpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (smpq *SysMenuParamQuery) Count(ctx context.Context) (int, error) {
	if err := smpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return smpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (smpq *SysMenuParamQuery) CountX(ctx context.Context) int {
	count, err := smpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (smpq *SysMenuParamQuery) Exist(ctx context.Context) (bool, error) {
	if err := smpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return smpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (smpq *SysMenuParamQuery) ExistX(ctx context.Context) bool {
	exist, err := smpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SysMenuParamQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (smpq *SysMenuParamQuery) Clone() *SysMenuParamQuery {
	if smpq == nil {
		return nil
	}
	return &SysMenuParamQuery{
		config:     smpq.config,
		limit:      smpq.limit,
		offset:     smpq.offset,
		order:      append([]OrderFunc{}, smpq.order...),
		predicates: append([]predicate.SysMenuParam{}, smpq.predicates...),
		// clone intermediate query.
		sql:    smpq.sql.Clone(),
		path:   smpq.path,
		unique: smpq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MenuID uint64 `json:"menu_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SysMenuParam.Query().
//		GroupBy(sysmenuparam.FieldMenuID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (smpq *SysMenuParamQuery) GroupBy(field string, fields ...string) *SysMenuParamGroupBy {
	grbuild := &SysMenuParamGroupBy{config: smpq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := smpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return smpq.sqlQuery(ctx), nil
	}
	grbuild.label = sysmenuparam.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MenuID uint64 `json:"menu_id,omitempty"`
//	}
//
//	client.SysMenuParam.Query().
//		Select(sysmenuparam.FieldMenuID).
//		Scan(ctx, &v)
func (smpq *SysMenuParamQuery) Select(fields ...string) *SysMenuParamSelect {
	smpq.fields = append(smpq.fields, fields...)
	selbuild := &SysMenuParamSelect{SysMenuParamQuery: smpq}
	selbuild.label = sysmenuparam.Label
	selbuild.flds, selbuild.scan = &smpq.fields, selbuild.Scan
	return selbuild
}

func (smpq *SysMenuParamQuery) prepareQuery(ctx context.Context) error {
	for _, f := range smpq.fields {
		if !sysmenuparam.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if smpq.path != nil {
		prev, err := smpq.path(ctx)
		if err != nil {
			return err
		}
		smpq.sql = prev
	}
	return nil
}

func (smpq *SysMenuParamQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SysMenuParam, error) {
	var (
		nodes = []*SysMenuParam{}
		_spec = smpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SysMenuParam).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SysMenuParam{config: smpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(smpq.modifiers) > 0 {
		_spec.Modifiers = smpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, smpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (smpq *SysMenuParamQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := smpq.querySpec()
	if len(smpq.modifiers) > 0 {
		_spec.Modifiers = smpq.modifiers
	}
	_spec.Node.Columns = smpq.fields
	if len(smpq.fields) > 0 {
		_spec.Unique = smpq.unique != nil && *smpq.unique
	}
	return sqlgraph.CountNodes(ctx, smpq.driver, _spec)
}

func (smpq *SysMenuParamQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := smpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (smpq *SysMenuParamQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sysmenuparam.Table,
			Columns: sysmenuparam.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: sysmenuparam.FieldID,
			},
		},
		From:   smpq.sql,
		Unique: true,
	}
	if unique := smpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := smpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysmenuparam.FieldID)
		for i := range fields {
			if fields[i] != sysmenuparam.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := smpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := smpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := smpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := smpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (smpq *SysMenuParamQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(smpq.driver.Dialect())
	t1 := builder.Table(sysmenuparam.Table)
	columns := smpq.fields
	if len(columns) == 0 {
		columns = sysmenuparam.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if smpq.sql != nil {
		selector = smpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if smpq.unique != nil && *smpq.unique {
		selector.Distinct()
	}
	for _, m := range smpq.modifiers {
		m(selector)
	}
	for _, p := range smpq.predicates {
		p(selector)
	}
	for _, p := range smpq.order {
		p(selector)
	}
	if offset := smpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := smpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (smpq *SysMenuParamQuery) Modify(modifiers ...func(s *sql.Selector)) *SysMenuParamSelect {
	smpq.modifiers = append(smpq.modifiers, modifiers...)
	return smpq.Select()
}

// SysMenuParamGroupBy is the group-by builder for SysMenuParam entities.
type SysMenuParamGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (smpgb *SysMenuParamGroupBy) Aggregate(fns ...AggregateFunc) *SysMenuParamGroupBy {
	smpgb.fns = append(smpgb.fns, fns...)
	return smpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (smpgb *SysMenuParamGroupBy) Scan(ctx context.Context, v any) error {
	query, err := smpgb.path(ctx)
	if err != nil {
		return err
	}
	smpgb.sql = query
	return smpgb.sqlScan(ctx, v)
}

func (smpgb *SysMenuParamGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range smpgb.fields {
		if !sysmenuparam.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := smpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := smpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (smpgb *SysMenuParamGroupBy) sqlQuery() *sql.Selector {
	selector := smpgb.sql.Select()
	aggregation := make([]string, 0, len(smpgb.fns))
	for _, fn := range smpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(smpgb.fields)+len(smpgb.fns))
		for _, f := range smpgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(smpgb.fields...)...)
}

// SysMenuParamSelect is the builder for selecting fields of SysMenuParam entities.
type SysMenuParamSelect struct {
	*SysMenuParamQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (smps *SysMenuParamSelect) Scan(ctx context.Context, v any) error {
	if err := smps.prepareQuery(ctx); err != nil {
		return err
	}
	smps.sql = smps.SysMenuParamQuery.sqlQuery(ctx)
	return smps.sqlScan(ctx, v)
}

func (smps *SysMenuParamSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := smps.sql.Query()
	if err := smps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (smps *SysMenuParamSelect) Modify(modifiers ...func(s *sql.Selector)) *SysMenuParamSelect {
	smps.modifiers = append(smps.modifiers, modifiers...)
	return smps
}
