// Code generated by ent, DO NOT EDIT.

package sysdictionary

import (
	"slash-admin/pkg/types"
	"time"
)

const (
	// Label holds the string label denoting the sysdictionary type in the database.
	Label = "sys_dictionary"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeDetails holds the string denoting the details edge name in mutations.
	EdgeDetails = "details"
	// Table holds the table name of the sysdictionary in the database.
	Table = "sys_dictionary"
	// DetailsTable is the table that holds the details relation/edge.
	DetailsTable = "sys_dictionary_detail"
	// DetailsInverseTable is the table name for the SysDictionaryDetail entity.
	// It exists in this package in order to avoid circular dependency with the "sysdictionarydetail" package.
	DetailsInverseTable = "sys_dictionary_detail"
	// DetailsColumn is the table column denoting the details relation/edge.
	DetailsColumn = "dictionary_id"
)

// Columns holds all SQL columns for sysdictionary fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldName,
	FieldStatus,
	FieldDesc,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus types.Status
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
