// Code generated by ent, DO NOT EDIT.

package bsuser

import (
	"fmt"
)

const (
	// Label holds the string label denoting the bsuser type in the database.
	Label = "bs_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the bsuser in the database.
	Table = "bs_users"
)

// Columns holds all SQL columns for bsuser fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPoints,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusPending Status = "pending"
	StatusActive  Status = "active"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusActive:
		return nil
	default:
		return fmt.Errorf("bsuser: invalid enum value for status field: %q", s)
	}
}
