// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CasbinRule is the predicate function for casbinrule builders.
type CasbinRule func(*sql.Selector)

// SysApi is the predicate function for sysapi builders.
type SysApi func(*sql.Selector)

// SysDictionary is the predicate function for sysdictionary builders.
type SysDictionary func(*sql.Selector)

// SysDictionaryDetail is the predicate function for sysdictionarydetail builders.
type SysDictionaryDetail func(*sql.Selector)

// SysMenu is the predicate function for sysmenu builders.
type SysMenu func(*sql.Selector)

// SysMenuParam is the predicate function for sysmenuparam builders.
type SysMenuParam func(*sql.Selector)

// SysOauthProvider is the predicate function for sysoauthprovider builders.
type SysOauthProvider func(*sql.Selector)

// SysRole is the predicate function for sysrole builders.
type SysRole func(*sql.Selector)

// SysToken is the predicate function for systoken builders.
type SysToken func(*sql.Selector)

// SysUser is the predicate function for sysuser builders.
type SysUser func(*sql.Selector)
